// frontend/lib/data.ts
// Mock data TripVote — porta da data.jsx
// Tutte le proposte sono per il viaggio "Capodanno a Tokyo"

import type { User, Board, Proposal, Category } from "./types";

export const TV_USERS: User[] = [
  { id: "u1", name: "Marco",    initials: "MB", color: "#DD5C36" },
  { id: "u2", name: "Giulia",   initials: "GR", color: "#149478" },
  { id: "u3", name: "Lorenzo",  initials: "LP", color: "#2E3A8C" },
  { id: "u4", name: "Sara",     initials: "SC", color: "#C68410" },
  { id: "u5", name: "Davide",   initials: "DV", color: "#C0364B" },
  { id: "u6", name: "Chiara",   initials: "CM", color: "#0F6E5C" },
  { id: "u7", name: "Federico", initials: "FT", color: "#7A4FBF" },
];

// Utente corrente (Marco)
export const TV_ME: User = TV_USERS[0];

export const TV_BOARDS: Board[] = [
  {
    id: "tokyo",
    title: "Capodanno a Tokyo",
    dates: "28 dic — 5 gen",
    cover: "https://images.unsplash.com/photo-1542051841857-5f90071e7989?w=1200&q=80",
    members: ["u1","u2","u3","u4","u5","u6","u7"],
    proposalsCount: 8,
  },
  {
    id: "lisbona",
    title: "Weekend a Lisbona",
    dates: "14 — 16 mar",
    cover: "https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=1200&q=80",
    members: ["u1","u2","u3"],
    proposalsCount: 4,
  },
  {
    id: "sicilia",
    title: "Road trip Sicilia",
    dates: "agosto — da definire",
    cover: "https://images.unsplash.com/photo-1601581875309-fafbf2d3ed3a?w=1200&q=80",
    members: ["u1","u2","u4","u5"],
    proposalsCount: 11,
  },
];

// Categorie proposta → label, pill CSS class, icona
export const TV_CAT: Record<string, Category> = {
  hotel:      { label: "Hotel",      pill: "tv-pill--coral",  icon: "bed" },
  flight:     { label: "Volo",       pill: "tv-pill--indigo", icon: "plane" },
  restaurant: { label: "Ristorante", pill: "tv-pill--amber",  icon: "fork" },
  activity:   { label: "Attività",   pill: "tv-pill--teal",   icon: "compass" },
  pin:        { label: "Pin mappa",  pill: "tv-pill--rose",   icon: "pin" },
};

// 8 proposte Tokyo — contenuto realistico
export const TV_PROPOSALS: Proposal[] = [
  {
    id: "p1",
    type: "hotel",
    title: "Park Hyatt Tokyo",
    subtitle: "Shinjuku · 5★ · vista skyline",
    image: "https://images.unsplash.com/photo-1540541338287-41700207dee6?w=1000&q=80",
    source: "booking.com",
    price: "€487",
    priceNote: "/notte",
    rating: 4.8,
    ratingCount: 1284,
    addedBy: "u2",
    addedAt: "2 ore fa",
    location: { lat: 35.6852, lng: 139.6907, address: "3-7-1-2 Nishi-Shinjuku" },
    note: "Quello di Lost in Translation. Spendiamo ma è iconico 🥃",
    votes: { yes: ["u1","u3","u6"], maybe: ["u4","u7"], no: ["u5"] },
    isNew: false,
  },
  {
    id: "p2",
    type: "flight",
    title: "ITA Airways FCO → HND",
    subtitle: "diretto · 12h 25m · 28 dic 13:45",
    image: "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=1000&q=80",
    source: "ita-airways.com",
    price: "€842",
    priceNote: "a/r p.p.",
    rating: null,
    addedBy: "u1",
    addedAt: "ieri",
    note: "Andata diretta, ritorno con scalo a Doha (più economico).",
    votes: { yes: ["u1","u2","u3","u6","u7"], maybe: ["u4"], no: [] },
    isNew: false,
  },
  {
    id: "p3",
    type: "hotel",
    title: "Hoshinoya Tokyo",
    subtitle: "Otemachi · ryokan moderno · onsen sul tetto",
    image: "https://images.unsplash.com/photo-1578469645742-46cae010e5d4?w=1000&q=80",
    source: "hoshinoresorts.com",
    price: "€612",
    priceNote: "/notte",
    rating: 4.9,
    ratingCount: 432,
    addedBy: "u4",
    addedAt: "5 ore fa",
    location: { lat: 35.6877, lng: 139.7672, address: "1-9-1 Otemachi" },
    note: "Ha l'onsen all'ultimo piano. Esperienza pazzesca.",
    votes: { yes: ["u2","u4","u6"], maybe: ["u1","u7"], no: [] },
    isNew: false,
  },
  {
    id: "p4",
    type: "restaurant",
    title: "Sukiyabashi Jiro Roppongi",
    subtitle: "Sushi · ★★★ Michelin · prenotazione 60gg",
    image: "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=1000&q=80",
    source: "tabelog.com",
    price: "€280",
    priceNote: "p.p.",
    rating: 4.7,
    addedBy: "u3",
    addedAt: "ieri",
    note: "Una sera ce la concediamo? Provo a prenotare appena escono i posti.",
    votes: { yes: ["u3","u2"], maybe: ["u1","u6","u7"], no: ["u4","u5"] },
    isNew: false,
  },
  {
    id: "p5",
    type: "activity",
    title: "TeamLab Planets",
    subtitle: "Toyosu · esperienza immersiva",
    image: "https://images.unsplash.com/photo-1554797589-7241bb691973?w=1000&q=80",
    source: "teamlab.art",
    price: "€26",
    priceNote: "p.p.",
    rating: 4.6,
    addedBy: "u6",
    addedAt: "3 g fa",
    note: "Prenotare slot mattina presto, evita la coda.",
    votes: { yes: ["u1","u2","u3","u4","u5","u6","u7"], maybe: [], no: [] },
    isNew: false,
  },
  {
    id: "p6",
    type: "pin",
    title: "Capodanno al Senso-ji",
    subtitle: "Asakusa · hatsumode tradizionale",
    image: "https://images.unsplash.com/photo-1583398701397-a0379b27e918?w=1000&q=80",
    source: "google.com/maps",
    price: null,
    addedBy: "u2",
    addedAt: "4 g fa",
    location: { lat: 35.7148, lng: 139.7967, address: "2-3-1 Asakusa" },
    note: "Il 31 a mezzanotte. Si suonano le campane 108 volte.",
    votes: { yes: ["u1","u2","u3","u4","u6"], maybe: ["u5","u7"], no: [] },
    isNew: false,
  },
  {
    id: "p7",
    type: "hotel",
    title: "Mustard Hotel Shibuya",
    subtitle: "Shibuya · boutique · €/qualità",
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1000&q=80",
    source: "mustardhotel.com",
    price: "€148",
    priceNote: "/notte",
    rating: 4.4,
    ratingCount: 612,
    addedBy: "u5",
    addedAt: "1 g fa",
    location: { lat: 35.6580, lng: 139.7016, address: "3-22-8 Shibuya" },
    note: "Più nei nostri budget. Posizione top.",
    votes: { yes: ["u3","u5","u7"], maybe: ["u1","u2","u4","u6"], no: [] },
    isNew: false,
  },
  {
    id: "p8",
    type: "activity",
    title: "Day trip a Hakone",
    subtitle: "Onsen + vista Fuji · treno + funivia",
    image: "https://images.unsplash.com/photo-1490806843957-31f4c9a91c65?w=1000&q=80",
    source: "japan-guide.com",
    price: "€95",
    priceNote: "p.p.",
    addedBy: "u7",
    addedAt: "appena ora",
    note: "Una giornata fuori Tokyo. Se siamo fortunati col Fuji vale tutto.",
    votes: { yes: ["u7"], maybe: [], no: [] },
    isNew: true,
  },
];
